Grievances/urls.py
from django.conf.urls import url
from views import GrievancesListView, AddGrievanceView
from django.contrib.auth.decorators import login_required
from Grievances import views
urlpatterns = [
                       url(r'^$', login_required(GrievancesListView.as_view()), name=u'list_grievance'),
                       url(r'^add/$', login_required(AddGrievanceView.as_view()), name=u'add_grievance'),
                       url(r'^escalate/$', login_required(views.EscalateGrievanceView), name=u'escalate_grievance'),
                       url(r'^rate_and_close/$', login_required(views.RateAndCloseView), name=u'rate_and_close'),
                       
                       ]

QMS/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import *
from .autocomplete_light_registry import *
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', login_required(AssessmentView.as_view()), name=u'qms'),
    url(r'^review/(?P<id>\d+)/(?P<chapter_component_id>\d+)/(?P<review_group_id>\d+)/$',
        login_required(ReviewRedirectView.as_view()), name= u'review_redirect_view'),

    url(r'^edit/$', login_required(ReviewReportManipulationView.as_view()), name='edit_review'),
    url(r'^choose_tabs/$', login_required(ChooseTabs.as_view()), name='choose_tabs'),
    url(r'^fetch_severity/$', login_required(fetch_severity), name=u'fetch_severity'),
    url(r'^fetch_author/$', login_required(fetch_author), name=u'fetch_author'),
    url(r'^chapter_summary/$', login_required(chapter_summary), name=u'chapter_summary'),
    url(r'^write_qms_chapter_level_summary/$', login_required(write_qms_chapter_level_summary),
        name=u'write_qms_chapter_level_summary'),
    url(r'^review_completed/$', login_required(review_completed), name=u'review_completed'),
    url(r'^mark_as_completed/$', login_required(mark_as_completed), name=u'tab_review_completed'),
    url(r'^get_template_process_review/$', login_required(get_template_process_review),
        name=u'get_template_process_review'),
    url(r'^AutocompleteDMProjects/$', login_required(AutocompleteDMProjects.as_view()), name='AutocompleteDMProjects',),
    url(r'^AutocompleteProjectQMS/$', login_required(AutocompleteProjectQMS.as_view()), name='AutocompleteProjectQMS', ),
    url(r'^AutocompleteUser/$', login_required(AutocompleteUser.as_view()), name='AutocompleteUser', ),
    url(r'^AutocompleteChapters/$', login_required(AutocompleteChapters.as_view()), name='AutocompleteChapters', ),
    url(r'^AutocompleteComponents/$', login_required(AutocompleteComponents.as_view()), name='AutocompleteComponents', ),
    url(r'^AutocompleteProcessModel/$', login_required(AutocompleteProcessModel.as_view()), name='AutocompleteProcessModel', ),
    url(r'^AutocompleteTemplates/$', login_required(AutocompleteTemplates.as_view()), name='AutocompleteTemplates', ),
    url(r'^AutocompleteReviewGroup/$', login_required(AutocompleteReviewGroup.as_view()), name='AutocompleteReviewGroup', ),
    url(r'^AutoCompleteUserProjectSpecific/$', login_required(AutoCompleteUserProjectSpecific.as_view()),
        name='AutoCompleteUserProjectSpecific', ),
    url(r'^AutoCompleteAssignUserProjectSpecific/$', login_required(AutoCompleteAssignUserProjectSpecific.as_view()),
        name='AutoCompleteAssignUserProjectSpecific', ),
    url(r'^AutoCompleteChapterSpecificComponent/$', login_required(AutoCompleteChapterSpecificComponent.as_view()),
        name='AutoCompleteChapterSpecificComponent', ),
    url(r'^dashboard/$', login_required(DashboardView.as_view()),  name='qms_dashboard'),# TemplateView.as_view(template_name='qms_dashboard.html')),
    url(r'^review_list/$', login_required(ReviewListView.as_view()), name='review_list'),
    url(r'^export_review/$', login_required(ExportReview.as_view()), name='export_review'),
                       ]

timetracker/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from MyANSRSource import apps
from django.conf import settings
from django.conf.urls.static import static


# Modify this to change the title from "Django Administration"

admin.site.site_header = apps.MyANSRSourceConfig.verbose_name +  \
    ' - Management UI'

urlpatterns = [
                       url(r'^grappelli/', include('grappelli.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^fb360/', include('fb360.urls')),
                       url(r'^myansrsource/', include('MyANSRSource.urls')),
                       url(r'session_security/',
                           include('session_security.urls')
                           ),
                       url(r'^$', RedirectView.as_view(url='/myansrsource/')),
                       url(r'^grievances/', include('Grievances.urls')),
                       url(r'^grievances_admin/', include('GrievanceAdmin.urls')),
                       url(r'^reports/', include('Reports.urls')),
                       url(r'^salesforce/', include('Salesforce.urls')),
                       url(r'^bookings/', include('BookMyRoom.urls')),
                       url(r'^leave/', include('Leave.urls')),
                       # url(r'^hire/', include('Hire.urls')),
                       # url(r'^exitapp/', include('ExitApp.urls')),
                       url(r'^library/', include('Library.urls')),
                       url(r'^laptop/', include('LaptopAvail.urls')),
                       url(r'^process/', include('CustomApp.urls')),
                       url(r'^skillset/', include('skillset.urls')),
                       url(r'^timein/', include('TimeInOffice.urls')),
                       url(r'^qms/', include('QMS.urls')),
                       ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Grievances/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime, os
from employee.models import TeamMember

from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.conf import settings

from django.core.validators import MinLengthValidator
from django.utils.safestring import mark_safe


SATISFACTION_CHOICES = (('satisfied', 'Satisfied'), ('not_sure', 'Not Sure'), ('dissatisfied', 'Dissatisfied'), ('very_dissatisfied', 'Very Dissatisfied') )
STATUS_CHOICES = (('new', 'New'), ('opened', 'Opened'), ('in_progress', 'In Progress'))
STATUS_CHOICES_CLOSED = (('new', 'New'), ('opened', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed'))

def change_file_path(instance, filename):
    
    ''' This function generates a random string of length 16 which will be a combination of (4 digits + 4
    characters(lowercase) + 4 digits + 4 characters(uppercase)) seperated 4 characters by hyphen(-) '''
    
    import random
    import string
    
    # random_str length will be 16 which will be combination of (4 digits + 4 characters + 4 digits + 4 characters)
    random_str =  "".join([random.choice(string.uppercase) for i in range(0,4)]) + "".join([random.choice(string.digits) for i in range(0,4)]) + \
                    "".join([random.choice(string.lowercase) for i in range(0,4)]) + "".join([random.choice(string.digits) for i in range(0,4)])
    
    # return string seperated by hyphen eg:
    random_str =  random_str[:4] + "-" + random_str[4:8] + "-" + random_str[8:12] + "-" + random_str[12:]
    filetype = filename.split(".")[-1].lower()
    filename = random_str +"." +  filetype
    path = "grievances/uploads/" + str(datetime.datetime.now().year) + "/" + str(datetime.datetime.now().month) + "/" + str(datetime.datetime.now().day) + "/"
    os_path = os.path.join(path, filename)
    return os_path



class Grievances_category(models.Model):
    
    category = models.CharField(max_length=200)
    active = models.BooleanField(blank=False, default=True, verbose_name="Is Active?")
    
    def __unicode__(self):
        ''' return unicode strings '''
        return '%s' % (self.category)

class Grievances(models.Model):
    user = models.ForeignKey(User)
    
    grievance_id = models.CharField(max_length=60, unique=True)
    category = models.ForeignKey(Grievances_category)
    subject = models.CharField(max_length=100, validators=[MinLengthValidator(15)])
    
    # length validations are different for front-end and backend. e.g js treats new line as 1 character and python treats the same as "\n" i.e 2
    #characters. So to be safe, we are giving length 200 characters more than what is validated in front-end(2000 characters)
    grievance = models.TextField(max_length=2200, validators=[MinLengthValidator(15)], help_text=mark_safe("<span id='textarea_remaining'>2000 remaining</span>"))
    
    action_taken = models.TextField(max_length = 2000, blank=True, null=True, validators=[MinLengthValidator(15)])
    user_closure_message = models.TextField(max_length = 2000, blank=True, null=True, validators=[MinLengthValidator(5)])
    admin_closure_message = models.TextField(max_length = 2000, blank=True, null=True, validators=[MinLengthValidator(5)])
    
    satisfaction_level = models.CharField(max_length = 50, blank=True, null=True, choices=SATISFACTION_CHOICES)
    
    escalate = models.BooleanField(default=False)
    escalate_to = models.CharField(max_length=200, blank=True, null=True, help_text="In case of multiple email id's, seperate them by a semicolan. Do not use single or double quotes anywhere")
    
    grievance_attachment  = models.FileField(upload_to=change_file_path, blank=True, null=True)
    admin_action_attachment = models.FileField(upload_to=change_file_path, blank=True, null=True)
    user_closure_message_attachment = models.FileField(upload_to=change_file_path, blank=True, null=True)
    admin_closure_message_attachment = models.FileField(upload_to=change_file_path, blank=True, null=True)
    
    created_date = models.DateTimeField(auto_now_add=True)
    action_taken_date = models.DateTimeField(blank=True, null=True)
    admin_closure_message_date = models.DateTimeField(blank=True, null=True)
    
    closure_date = models.DateTimeField(blank=True, null=True)
    
    active = models.BooleanField(blank=False, default=True, verbose_name="Is Active?")
    grievance_status = models.CharField(max_length=50, blank=False, null=False, default="new", choices=STATUS_CHOICES_CLOSED)
    
    def __unicode__(self):
        """ return unicode strings """
        return '%s' % (self.grievance_id)
    
    class Meta:
        verbose_name_plural = "Grievances"

Grievances/forms.py
from models import Grievances, SATISFACTION_CHOICES, Grievances_category
from django.utils.safestring import mark_safe

from django import forms
class AddGrievanceForm(forms.ModelForm):
    grievance_attachment = forms.FileField(label='Attachment', required=False, help_text=mark_safe("Allowed file types: jpg, csv, png, pdf, xls, xlsx, doc, docx, jpeg.<br>Maximum allowed file size: 1MB"))
    # Add Bootstrap widgets
    grievance_attachment.widget.attrs = {'class':'filestyle', 'data-buttonBefore':'true', 'data-iconName':'glyphicon glyphicon-paperclip'}
    
    category = forms.ModelChoiceField(queryset=Grievances_category.objects.filter(active=True), empty_label="---------")
    # Add Bootstrap widgets
    category.widget.attrs = {'class': 'form-control', 'required':'true'}
    
    subject = forms.CharField(max_length=100)
    # Add Bootstrap widgets
    subject.widget.attrs = {'class': 'form-control', 'required':'true', 'maxlength':'100', 'placeholder':'Max 100 characters'}
    
    class Meta:
        model = Grievances
        fields = ['category', 'subject', 'grievance', 'grievance_attachment']
        
        widgets = {
          'grievance': forms.Textarea(attrs={'class': 'form-control', 'rows':8, 'cols':70, 'required':'true','placeholder':'Max 2000 characters'}),
        }

    
    def clean(self):
        '''  Custom clean method. Validations for spaces for input fields '''
        
        if self.cleaned_data.get('subject', ''):
            self.cleaned_data['subject'] = self.cleaned_data['subject'].strip()
        if self.cleaned_data.get('grievance', ''):
            self.cleaned_data['grievance'] = self.cleaned_data['grievance'].strip()
        
        return self.cleaned_data

Grievances/templates/add_grievance.html
{% load grievances_template_tags %}
{% if record_added %}
   <!--	  Record added. Return the added record in a table row - Ajax-->
				<tr class="warning" style="border-bottom: 1px solid #DBD9D9">
							<td style="width: 15%">
								<p>{{object.grievance_id}}</p>
								
								<br><label type="label" class="label label-info new_notification"> New </label>
								
							</td>
							
							
							<td style="width: 50%">
							 <!--	Grievance details - grievance, action taken, user actions, HR closure message -->
									{% include 'grievance_details.html' %}
							</td>
							
							<td style="width: 15%">
								<p class="text-center">{{object.category}}</p>
							</td>
	
							<td style="width: 15%">
								{{object.created_date}}
							</td>
							<td>
							  {% if object.active %}
								 <p class="text-center"> 
									<span id="status_{{object.grievance_id}}" > <i class="fa fa-unlock fa-lg" style="color:#66B778;"></i> </span>
								 </p>
							  {% else %}
								  <p class="text-center">
									<span> <i class="fa fa-lock fa-lg" style="color:#d9534f;"></i> </i> </span>
								  </p>
								  
								  
							  {% endif %}
							</td>
							
						</tr>

{% elif add %}

			<!-- Ajax -->
		 <div id="ajax_loader_add_greivance_form" class="ajax_bck"><div class="ajax_load_image"></div></div>
		 
		 <form id="add_greivance_form" method="post" enctype="multipart/form-data">
		 <!--<form action="{% url 'add_grievance' %}" method="post">-->
		  {% csrf_token %}
		 
			 <table border="0" style="margin:0 auto">
			   <div style="color:red" id="AddGrievanceForm_errors"></div><br>
						 {% for field in form.visible_fields %}
						   <tr>
						   <td style="padding:20px 20px 5px 5px;">{{ field.label_tag }} {% if field.field.required %}<span style="color:red;">*</span>{% endif %} <br></td>
						   <td><br>{{ field }}{% if field.help_text %} {{ field.help_text }} {% endif %}
							   {% if field.errors %}<p style="color:red;">{{ field.errors|striptags }}</p>{% endif %}
						   </td>
						   </tr>
						{% endfor %}
						 {% if errors %}
						   <tr>
							{% for non_field_error in errors %}
							 <td></td>
							  <td><div style="color:red;"><h5> {{non_field_error}}</h5></div></td>
							{% endfor %}
							</tr>
						 {% endif %}
						 {% for field in form.hidden_fields %}
							 {{field}}
						 {% endfor %}
						 
						
			 </table>
			 <h3 class="text-center"><input type="submit" class="btn btn-danger" value="Submit"/></h3>
		  </form>
		   <script>
			
			$(document).ready(function() {
						$('#id_grievance').attr('maxlength','');
						var text_max = 2000;
						var text_length = $('#id_grievance').val().length;
						var text_remaining = text_max - text_length;
						$('#textarea_remaining').html(text_max + ' characters remaining');
						
						$('#id_grievance').keyup(function() {
							text_length = $('#id_grievance').val().length;
							text_remaining = text_max - text_length;
							if (text_length > 2000) {
								$('#id_grievance').val($('#id_grievance').val().slice(0,2000))
								
								// the length changes in the above line
								text_length = $('#id_grievance').val().length;
							    text_remaining = text_max - text_length;
							}
							$('#textarea_remaining').html(text_remaining + ' characters remaining');
						});
					});
			
				 // File size validation
				var fileExtension = ['jpg', 'csv','png', 'pdf', 'xlsx', 'xls', 'docx', 'doc', 'jpeg', 'eml'];
				$('.filestyle').bind('change', function() {
				if (this.files[0].size > 1000000) {
					alert("File size greater than 1MB not allowed");
					$(this).filestyle('clear');
				}
				else
				{
					if ($.inArray($(this).val().split('.').pop().toLowerCase(), fileExtension) == -1) {
                    alert("Allowed file types : "+fileExtension.join(', '));
                    $(this).filestyle('clear');
                }
				}
                
				});
			
				  $("form#add_greivance_form").submit(function(){
						
						 var formData = new FormData($(this)[0]);
						 form_id = $(this)[0].id;
						 form_element = $(this);
						ajax_loader_element = $('#ajax_loader_add_greivance_form');
						 
						 swal({   title: "Are you sure?",
							text: "You will not be able to edit this grievance after submission!",
							type: "warning",
							showCancelButton: true,
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "Yes, Submit it!",
							cancelButtonText: "cancel",
							closeOnConfirm: true,
							closeOnCancel: true
							},
							function(isConfirm){
								// If user clicks on ok;
								if (isConfirm) {
									 
								 ShowAjaxLoader(ajax_loader_element, form_element.width(), form_element.height());
								 $.ajax({
									url: "/grievances/add/",
									type: 'post',
									data: formData,
									success: function (data) {
									   if (data.record_added) {
										  $("#modal_body").html("<h5 style='color:green;'>" + data.success_msg + "</h5>");
										  window.location.reload();
										 }
									   else{
										$("#modal_body").html(data);
									   }
										HideAjaxLoader($('#ajax_loader_add_greivance_form'));
										
										reloadJS();
									},
									error: function(XMLHttpRequest, textStatus, errorThrown) {
												$("#AddGrievanceForm_errors").html("Oops! Something went wrong on the server. The details are below: " 
													+ "<br>Status : "+ textStatus + "<br>Exception : " + errorThrown + "<br><br> Please take a screenshot of this message and send it to <a href='mailto:myansrsourceHelpDesk@ansrsource.com'> MyAnsrSource Help Desk</a>.");
												HideAjaxLoader(ajax_loader_element);
											},
												
									cache: false,
									contentType: false,
									processData: false
								 });
								} 
							   });
						
						 return false;
					 });
			  </script>

 {% else %}
  
  None
   
 {% endif %}
	
	
   

Grievances/templates/grievances_list.html
{% extends 'master.html' %}
{% load bootstrap3 %}
{% load fontawesome %}
{% load static from staticfiles %}
{% load grievances_template_tags %}

{% block siteTitle %}Grievances{% endblock %}
{% block pageTitle %}Grievances{% endblock %}
{% block content  %}
		
<!--	fixed left section	-->
<!-- 		<div class="HowItWorksContainer how_it_works_hide">
			<div class="DivRotate DivVer"><h3>How it works</h3></div>
			
			<div class="HowitWorksContent animated ">
				<ol>
					<li>You register a grievance.</li>
					<li>Admin takes action accordingly.</li>
					<li>If you are satisfied with the action taken, close the grievance. If not, escalate.</li>
					<li>Admin forwards the grievance to the concerned authority.</li>
					<li>The authority takes action.</li>
					<li>You close the grievance. </li>
				</ol>
			</div>
		</div> -->
<!-- Add grievance popup-->
<div class="modal fade" id="add_grievance_popup" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				
				<div class="modal-header vd_bg-blue vd_white">
					 
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
						<span class="glyphicon glyphicon glyphicon-remove"></span>
					</button>
					<h4 class="modal-title" id="myModalLabel">
						<h3 class="text-center">Register Grievance</h3>
					</h4>
				</div>
				<div class="modal-body" id="modal_body">
					Loading..please wait..
				</div>
                        <div class="modal-footer background-login">
                          <button type="button" class="btn vd_btn vd_bg-grey" data-dismiss="modal">Close</button>
{#                          <button type="button" class="btn vd_btn vd_bg-green">Save changes</button>#}
                        </div>
				
			</div>
		</div>
</div>
<!-- End add grievance popup -->









<!-- 
{% if objects_list %}
					<h5 class="text-center">( Your Grievances )</h5>
{% endif %} -->

<h4 class="margin-left-15" >
			<div class="pull-left total-greivances">Total : {{objects_list|length}}</div>
		  <a class="launchModalForm pull-right margin-right-15" href="#add_grievance_popup" role="button" class="btn" data-toggle="modal"><button type="button" class="btn btn-danger">Register a grievance</button></a>
</h4>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<table class="table table-hover table-striped">


















				<thead class="panel-heading-styles">
					<tr class="TbHead">
						<th style="width: 7%">
							Sr. No.
						</th>
						<th>
							Grievance ID
						</th>
						<th>
							Grievance / Feedback / Actions
						</th>
						<th>
							Category
						</th>
						<th>
							Registered Date
						</th>
						<th>
							Status
						</th>
					</tr>
				</thead>





				
				<tbody id="listTableBody">
					{% if objects_list %}
						{% for object in objects_list %}
							
						<tr class="" style="border-bottom: 1px solid #DBD9D9">
							<td >
								<p>{{forloop.counter}}</p>
							</td>
							<td style="width: 15%">
								<p>{{object.grievance_id}}</p>
								
								{% if object.escalate %}<p><label type="label" class="label label-warning">Escalated</label></p> {% endif %}
								
								
								
								{% if object.satisfaction_level == 'satisfied' or object.satisfaction_level == 'not_sure'%}
									<div>
										<label type="label" class="label label-success ">{{object.get_satisfaction_level_display}}</label>
									</div>
									
								{% endif %}
								
								{% if object.satisfaction_level == 'dissatisfied' or object.satisfaction_level == 'very_dissatisfied'%}
									<div>
										<label type="label" class="label label-danger ">{{object.get_satisfaction_level_display}}</label>
									</div>
								{% endif %}
								
							</td>
							
							<td style="width: 50%">
								<!--	Grievance details - grievance, action taken, user actions, HR closure message -->


									{% include 'grievance_details.html' %}


							</td>
							
							<td style="width: 15%">
								<p>{{object.category}}</p>
							</td>
	
							<td style="width: 15%">
								<p>{{object.created_date}}</p>
							</td>
							<td>
								{% if object.grievance_status == 'new' %}<p id="status_{{object.grievance_id}}"><label type="label" class="label label-info">New</label></p> {% endif %}
								{% if object.grievance_status == 'opened' %}<p id="status_{{object.grievance_id}}"><label type="label" class="label label-warning">Open</label></p> {% endif %}
								{% if object.grievance_status == 'in_progress' %}<p id="status_{{object.grievance_id}}"><label type="label" class="label label-success">In Progress</label></p> {% endif %}
								{% if object.grievance_status == 'closed' %}<p id="status_{{object.grievance_id}}"><label type="label" class="label label-danger">Closed</label></p> {% endif %}
								
							</td>
						
							
						</tr>
						
						{% endfor %}
					
						
					{% endif %}
				</tbody>














			
			</table>
		</div>
	</div>
</div>

{% if not objects_list %}
							<div>
								<h4 class="text-center" id="no_grievances_alert">No grievances found..</h4><br><br>
						</div>
{% endif %}
<h5 class="text-center">Very often, problems go unnoticed. If you don't tell us about them, we won't be able to fix them. Please share your grievances with us if any, so that we can improve your experience at <strong>ansr</strong>source.</h5>



















{% endblock  %}

{% block page_specific_JS %}
		<script src='/static/js/jquery.ui.widget.js' type="text/javascript"></script>
		<script src='/static/js/bootstrap-filestyle.min.js' type="text/javascript"></script>
		<script src='/static/js/grievances_user.js' type="text/javascript"></script>

{% endblock %}

Grievances/templates/submit_user_actions.html
{% load grievances_template_tags %}
{% if record_added %}

<h5 style="color:green"> Thank you for your feedback. </h5>

        
        {% if object.satisfaction_level == 'satisfied' or object.satisfaction_level = 'not_sure'%}
            <div>
                <p><b>Satisfaction level : </b> <label type="label" class="label label-success ">{{object.get_satisfaction_level_display}}</label></p>
            </div>
            
        {% endif %}
        
        {% if object.satisfaction_level == 'dissatisfied' or object.satisfaction_level = 'very_dissatisfied'%}
            <div>
                <p><b>Satisfaction level : </b><label type="label" class="label label-danger ">{{object.get_satisfaction_level_display}}</label></p>
            </div>
        {% endif %}
        {% if object.user_closure_message %}<b> Message </b>: {{object.user_closure_message}}{% endif %}
        
        <!-- Attachments start -->
        {% if object.user_closure_message_attachment%}<p></p><i><b>Attachment : </b></i> <p></p>
            <a target="_blank" href="{{object.user_closure_message_attachment.url}}">
                {% if object.user_closure_message_attachment.name|GetFileTypeFromName == 'xls' or object.user_closure_message_attachment.name|GetFileTypeFromName == 'xlsx' %}
                    <img alt="An XLS file" src="/static/images/file_type_icons/xls_icon.png" height="50px" width="50px">
                {% elif object.user_closure_message_attachment.name|GetFileTypeFromName == 'csv' %}
                    <img alt="A csv file" src="/static/images/file_type_icons/csv_icon.png" height="50px" width="50px">
                {% elif object.user_closure_message_attachment.name|GetFileTypeFromName == 'pdf' %}
                    <img alt="A pdf file" src="/static/images/file_type_icons/pdf_icon.png" height="50px" width="50px">
                {% elif object.user_closure_message_attachment.name|GetFileTypeFromName == 'doc' or object.user_closure_message_attachment.name|GetFileTypeFromName == 'docx'  %}
                    <img alt="A doc file" src="/static/images/file_type_icons/doc_icon.png" height="50px" width="50px">
                {% elif object.user_closure_message_attachment.name|GetFileTypeFromName == 'jpg' or object.user_closure_message_attachment.name|GetFileTypeFromName == 'jpeg' or object.user_closure_message_attachment.name|GetFileTypeFromName == 'png' %}
                    <img alt="A doc file" src="{{object.user_closure_message_attachment.url }}" height="50px" width="50px">
                {% endif %}
            </a>
        {% endif %}
        <!-- Attachments end -->
        
         {% if object.closure_date%}<h5><div style="float: right;"><p></p><p>-<i>{{object.closure_date}}</i></p></div></h5>{% endif %}
         
         <br>

{% endif %}